name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  jira-project-url:  # id of input
    description: 'Who to greet'
    required: true
  GITHUB_TOKEN:
    description: 'Add token'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'