name: 'JIRA Ticket commenter'
description: 'Tags JIRA ticket link'
inputs:
  jira-project-url:
    description: 'Link of your project URL'
    required: true
  GITHUB_TOKEN:
    description: 'Add token'
    required: true
runs:
  using: 'node16'
  main: 'index.js'